### ISSUE TITLE
Missing flutter-opendroneid library

### ISSUE THREAD

**Issue by aaronpk** [dronetag/drone-scanner#1]
Hello! I tried building this, but I get an error:

> Because drone_scanner depends on flutter_opendroneid from path which doesn't exist (could not find package flutter_opendroneid at "../flutter-opendroneid"), version solving failed.

I see a reference to this in the pubconf.yaml file:

> flutter_opendroneid:
>    path: ../flutter-opendroneid

I didn't find this library on GitHub though!

**Comment by matejglejtek** [comment]
Hello, 
we are currently in process of publishing the library, we expect that it will be available next week.

**Comment by matejglejtek** [comment]
Hi, library was published few weeks ago, you will be now able to build the application.
