### ISSUE TITLE
Drone Scanner failed to detect and OpenDroneID successfully detected DJI Air 2S WiFi Beacon.

### ISSUE THREAD

**Issue by overdrive31** [dronetag/drone-scanner#25]
In an attempt to test Remote ID detection from a friend’s DJI Air 2S which uses WiFi Beacon. Drone Scanner failed to detect, while OpenDroneID immediately detected the drone using my Samsung Note 20 5G. I should note, that my Note 20 5G’s Developer settings were set to Disable WiFi Scan Throttling as per OpenDroneID’s suggestions. Drone Scanner Preferences stated that the Note 20 5G’s WiFi Beacon Remote ID was Fully Supported. Yet it didn’t work and OpenDroneID did work. It appears this needs fixing.

**Comment by marianhlavac** [comment]
Thanks for reporting the issue.

We've addressed this issue in the latest version of [our opendroneid library](https://github.com/dronetag/flutter-opendroneid) and will be releasing fixed version of Drone Scanner to app stores in the next few days.
