### ISSUE TITLE
Hard Crash - Area Radius

### ISSUE THREAD

**Issue by JustDaveIII** [dronetag/drone-scanner#55]
The IOS app (v1.8.1) will crash when the Area Radius (in the Operator ID section) exceeds 259 meters.  260 will crash it. 

The radius is divided by 10 before transmitting. So this app needs to multiply by 10 to display.

A WAG is that a display var is a byte and a int is what's needed. ICBW.

**Comment by matejglejtek** [comment]
Fixed in the version 1.8.5 by updating [flutter-opendroneid](https://pub.dev/packages/flutter_opendroneid/changelog) package.

**Comment by JustDaveIII** [comment]
Ant idea when a new IOS app will be published with this and other bug fixes?
