### ISSUE TITLE
APK in GitHub releases?

### ISSUE THREAD

**Issue by Manouchehri** [dronetag/drone-scanner#77]
Would it be possible to upload the APK to GitHub releases as well? (I ended up downloading it off a third-party website, but would be handy if I didn't have to do that.)

Thanks!

**Comment by marianhlavac** [comment]
Hey @Manouchehri, thanks for the suggestion. We'll add it to our CI pipeline so the latest version is always attached in the releases as an APK.

**Comment by v0l** [comment]
Can you do [Obtanium](https://github.com/ImranR98/Obtainium) compatible releases?

**Comment by marianhlavac** [comment]
@v0l Sorry, we don't have an usecase for Obtanium currently, but we'll be glad to accept any contribution & help with the infra needed to push updates to Obtanium.

**Comment by v0l** [comment]
@marianhlavac All you need to do is name the APK files in a certain way on the release and it should work
